/**
 * Finnish postal code distance calculator.
 *
 * Uses a static coordinate lookup (generated by scripts/fetch-postal-coordinates.ts)
 * and haversine formula for real-world km distances.
 */

import postalData from "@/data/postal-coordinates.json";

// ─── Types ──────────────────────────────────────────────────────

interface Coordinates {
  lat: number;
  lng: number;
}

// Build a Map for O(1) lookups
const coordMap = new Map<string, Coordinates>();
for (const entry of postalData as { code: string; lat: number; lng: number }[]) {
  coordMap.set(entry.code, { lat: entry.lat, lng: entry.lng });
}

// ─── Haversine ──────────────────────────────────────────────────

const R = 6371; // Earth radius in km

function toRad(deg: number): number {
  return (deg * Math.PI) / 180;
}

/**
 * Haversine distance between two coordinates in kilometers.
 */
export function haversineKm(a: Coordinates, b: Coordinates): number {
  const dLat = toRad(b.lat - a.lat);
  const dLng = toRad(b.lng - a.lng);
  const sinLat = Math.sin(dLat / 2);
  const sinLng = Math.sin(dLng / 2);
  const h =
    sinLat * sinLat +
    Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * sinLng * sinLng;
  return R * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h));
}

// ─── Public API ─────────────────────────────────────────────────

/**
 * Get coordinates for a Finnish postal code.
 * Returns null if not found.
 */
export function getCoordinates(postalCode: string): Coordinates | null {
  return coordMap.get(postalCode) ?? null;
}

/**
 * Distance in km between two Finnish postal codes.
 * Returns null if either postal code is unknown.
 */
export function postalDistanceKm(
  codeA: string,
  codeB: string
): number | null {
  const a = coordMap.get(codeA);
  const b = coordMap.get(codeB);
  if (!a || !b) return null;
  return haversineKm(a, b);
}

/**
 * Average distance from a postal code to a list of other postal codes.
 * Skips unknown codes. Returns null if no valid pairs.
 */
export function averageDistanceKm(
  fromCode: string,
  toCodes: string[]
): number | null {
  const from = coordMap.get(fromCode);
  if (!from) return null;

  let sum = 0;
  let count = 0;
  for (const code of toCodes) {
    const to = coordMap.get(code);
    if (to) {
      sum += haversineKm(from, to);
      count++;
    }
  }
  return count > 0 ? sum / count : null;
}

/**
 * Total postal codes loaded.
 */
export const postalCodeCount = coordMap.size;
